version: "3.8"
services:
#  mongo:
#    image: mongo:6
#    container_name: mongodb-secure
#    restart: always
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongo-data:/data/db

  app:
    build: .
    container_name: habit-rhythm-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/habit-rhythm
      - NEXTAUTH_SECRET=your-random-secret
      - GITHUB_ID=your_github_client_id
      - GITHUB_SECRET=your_github_client_secret
      - GOOGLE_CLIENT_ID=your_google_client_id
      - GOOGLE_CLIENT_SECRET=your_google_client_secret
    depends_on:
      - mongo

volumes:
  mongo-data:
